### ISSUE TITLE
Carthage not working properly

### ISSUE THREAD

**Issue by catalandres** [zenangst/Hue#11]
I am getting the following output:

```
% carthage update
*** Fetching Hue
No tagged versions found for github "hyperoslo/Hue"
```

**Comment by zenangst** [comment]
Hey @catalandres, `Hue` hasn't been released yet so you'll have to specify to use `master` in your Cartfile.

```
github "hyperoslo/Hue" "master"
```

Let us know if that helps.

**Comment by catalandres** [comment]
It totally does.
Sorry for following the instructions a bit too literally! #newb :)

**Comment by zenangst** [comment]
@catalandres no worries mate, glad we could help!
