### ISSUE TITLE
TableView's gradients cut off in landscape

### ISSUE THREAD

**Issue by OptTrader** [zenangst/Hue#20]
Hey I have a simple question. Have a split view controller that I am testing with Hue. Using your demo example, how do I modify it so that in landscape view the whole tableview has the gradients instead of partially cut off?

**Comment by zenangst** [comment]
Hey @OptTrader, if you orientation changes then we need to redraw the layer with a new frame. I think we could fix this by implementing a redraw method in `viewWillTransitionToSize`.

**Comment by zenangst** [comment]
Sorry for the late response btw 😁
