### ISSUE TITLE
Carthage problems when compiling with flag "--platform iOS"

### ISSUE THREAD

**Issue by jorgej-ramos** [zenangst/Hue#33]
Hello all,

I'm getting the following error when trying to install Hue via Carthage:

`warning: no umbrella header found for target 'Hue-iOS', module map will not be generated`

The shell task exits with code 65.
Any idea?

Thank you

**Comment by zenangst** [comment]
Hey @think-dev, I haven't seen this before. Will look into and get back to you (sorry for the delayed response).

**Comment by jorgej-ramos** [comment]
Thank you @zenangst. Hue is a must on any project!

**Comment by zenangst** [comment]
@think-dev aww thanks man! So I looked into it, could you try the `add/umbrella-header` branch to see if that fixes the issue?

**Comment by jorgej-ramos** [comment]
Ok I'll try this weekend and will be back with the report. Thank you @zenangst

**Comment by zenangst** [comment]
Fixed by updating to new version of `Carthage`.

> Sorry for the delay! It seems that updating Carthage to 0.18.1 solves the problem, so you can close this issue.

Reference: #35
