### ISSUE TITLE
Ambiguous use of 'init(hex:)'

### ISSUE THREAD

**Issue by robertodias180** [zenangst/Hue#41]
Started getting this error:

Ambiguous use of 'init(hex:)' with let color = UIColor(hex: "#ff9000")

Any ideias?

**Comment by zenangst** [comment]
Hey @robertodias180, which version of `Hue` and which version of Swift are you using?
Seems odd to me but the snippet that you shared should work.

Could you share anything more from your implementation?

**Comment by zenangst** [comment]
ping @robertodias180

**Comment by robertodias180** [comment]
Sorry for the delay. Ended up find the issue, some other library had an internal method with the same name. And due to swift global imports gave me conflict.

**Comment by zenangst** [comment]
@robertodias180 oh, nice that you found the issue and that we weren't at fault 😎
Cheers mate 🍻

**Comment by guoyingtao** [comment]
@robertodias180 I met the same problem. How did you fix it? Thanks.

**Comment by robertodias180** [comment]
@guoyingtao since some other lib already had the same methods I just removed Hue from the project

**Comment by guoyingtao** [comment]
I am using Spring and Hue. It seems these two library have some conflicts. Thanks for your answer, I might as well remove Hue also.

**Comment by robertodias180** [comment]
@guoyingtao I had this issue also with Spring.

**Comment by zenangst** [comment]
Could this be solved by using the module namespace?
