### ISSUE TITLE
Version for swift 2.3

### ISSUE THREAD

**Issue by ghost** [zenangst/Hue#43]
How to get version for Swift 2.3?

**Comment by zenangst** [comment]
Hey @Domsware, we never made a Swift 2.3 version as we jumped directly to Swift 3.0. We tend to just support what we need ourselves out of the box and have the community contribute with anything else that might be needed. This way we are in "front". Also, seeing that `2.3` will be deprecated soon, we didn't feel that it was worth the investment.

> Xcode 8.2 is the last release that will support Swift 2.3.  Please migrate your projects to Swift 2.3 code to Swift 3 syntax by opening the project and choosing Edit > Convert > To Current Swift Syntax.

What you can do to get support for Swift 2.3 is to fork the repo, checkout version `1.3.0` or the commit just before `2.0.0` was merged. And then migrate the source code to Swift 2.3. It shouldn't be that much to change.

Closing this issue now.
