### ISSUE TITLE
Image colors white for all except background

### ISSUE THREAD

**Issue by damirstuhec** [zenangst/Hue#44]
I'm trying out image colors functionality and no matter which image I use it returns white color for primary, secondary and detail. Background color seems to work.

**Comment by avjinder** [comment]
Same here, all the colors returned are white except the background color. 
I printed the colors which were white and all of them had this value:

    UIExtendedSRGBColorSpace 1 1 1 1

**Comment by onmyway133** [comment]
@damirstuhec @avjinder Hi, I think this problem arose during swift 3 transition. Mind making a PR 😉
