### ISSUE TITLE
It doesn't go back to the main thread.  In UIImage+Hue.swift file.

### ISSUE THREAD

**Issue by hanks-hu** [zenangst/Hue#52]
<img width="643" alt="qq20180518-112015 2x" src="https://user-images.githubusercontent.com/16836336/40214476-8c5b5bfe-5a8d-11e8-9a1a-6dca3c1748e8.png">

**Comment by zenangst** [comment]
Hey @HanksHu,

Sorry for the delay. However, I do have some good news, I've taken over maintenance and further development of Hue and will continue to push things forward from here on end.

Again, sorry for the lack of responses here.

**Comment by zenangst** [comment]
Also, I've made a PR #60 to fix this issue.
