### ISSUE TITLE
Please add support for Swift Package Manager

### ISSUE THREAD

**Issue by appcornerit** [zenangst/Hue#69]
Xcode 11 support swift package manager, please add support for installing this project with the Swift Package Manager.

**Comment by zenangst** [comment]
@appcornerit hey mate, if you make a PR to add this as a feature I'd gladly review it 😎

**Comment by liuwin7** [comment]
Can you review this pull request https://github.com/zenangst/Hue/pull/70 ?
@zenangst

**Comment by zenangst** [comment]
@liuwin7 of course, sorry for the delay. I just have one small nitpick with the PR and that is with regards to the framework/package name. Is it via convention to include the underlying framework in the package name?

**Comment by zenangst** [comment]
Fixed by #70

**Comment by j-f1** [comment]
Can you tag a new release so we can add the package with just the GitHub URL instead of having to specify the commit?

**Comment by zenangst** [comment]
Hey @j-f1, I've added a new tag now. You can find it here - https://github.com/zenangst/Hue/releases/tag/5.0.1
